### ISSUE TITLE
roBa にて zmk-layout-shift 適用時に Build Error 発生

### ISSUE THREAD

**Issue by tokinarazu** [kot149/zmk-layout-shift#1]
### Description
roBa にて zmk-layout-shift 適用時に Build Error 発生 

### Environment
以下の roBa Github Action での Build
https://github.com/tokinarazu/zmk-config-roBa/actions/runs/15659350412/job/44114840736#step:11:286

エラー内容は、以下
```
[142/371] Building C object zephyr/CMakeFiles/zephyr.dir/tmp/zmk-config/zmk-layout-shift/src/behavior_layout_shift_key_press.c.obj
FAILED: zephyr/CMakeFiles/zephyr.dir/tmp/zmk-config/zmk-layout-shift/src/behavior_layout_shift_key_press.c.obj 
...(省略)...
/tmp/zmk-config/zmk-layout-shift/src/behavior_layout_shift_key_press.c:103:5: warning: braces around scalar initializer
  103 |     .parameter_metadata = {
      |     ^
/tmp/zmk-config/zmk-layout-shift/src/behavior_layout_shift_key_press.c:103:5: note: (near initialization for 'behavior_layout_shift_key_press_driver_api.parameter_metadata')
/tmp/zmk-config/zmk-layout-shift/src/behavior_layout_shift_key_press.c:104:9: error: field name not in record or union initializer
  104 |         .count = 1,
      |         ^
compilation terminated due to -Wfatal-errors.
```

解消方法はありますでしょうか。

**Comment by tokinarazu** [comment]
roBa 側の west.yml の情報も添付します。

```
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
    - name: kloir-z
      url-base: https://github.com/kloir-z
    - name: caksoylar  # <-- new entry
      url-base: https://github.com/caksoylar
    - name: kot149
      url-base: https://github.com/kot149
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kloir-z
      revision: scroll-acceleration-feature
    - name: zmk-rgbled-widget  # <-- new entry
      remote: caksoylar
      revision: main
    - name: zmk-layout-shift
      remote: kot149
      revision: v1
  self:
    path: config
```
